// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4YL5RtxAKJqhAlqRpBuVeSIBUJVN51A',
    appId: '1:207121966064:web:6d63043cffd9cae7b97335',
    messagingSenderId: '207121966064',
    projectId: 'sanaa-inventory-app',
    authDomain: 'sanaa-inventory-app.firebaseapp.com',
    storageBucket: 'sanaa-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKe89dIA9LlYcXB-gfbq_EgnBzAkEGxZE',
    appId: '1:207121966064:android:f0dccf55179db89fb97335',
    messagingSenderId: '207121966064',
    projectId: 'sanaa-inventory-app',
    storageBucket: 'sanaa-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwAlifz3LDWLTqqXCYHsnrxhEUkm2C4I4',
    appId: '1:207121966064:ios:addbe57b49869e12b97335',
    messagingSenderId: '207121966064',
    projectId: 'sanaa-inventory-app',
    storageBucket: 'sanaa-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwAlifz3LDWLTqqXCYHsnrxhEUkm2C4I4',
    appId: '1:207121966064:ios:addbe57b49869e12b97335',
    messagingSenderId: '207121966064',
    projectId: 'sanaa-inventory-app',
    storageBucket: 'sanaa-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4YL5RtxAKJqhAlqRpBuVeSIBUJVN51A',
    appId: '1:207121966064:web:f95f88b33afaa243b97335',
    messagingSenderId: '207121966064',
    projectId: 'sanaa-inventory-app',
    authDomain: 'sanaa-inventory-app.firebaseapp.com',
    storageBucket: 'sanaa-inventory-app.firebasestorage.app',
  );
}
